### ISSUE TITLE
Ported to Ruby

### ISSUE THREAD

**Issue by PhilT** [wolfgarbe/symspell#1]
I hope you don't mind, I ported your C# code to Ruby. 

https://github.com/PhilT/symspell

I've only just got it working and it's late so committing what I have now. Let me know if you'd like me to put any more of the original project details/copyright etc in my port.

Thanks for sharing!

**Comment by wolfgarbe** [comment]
Hi Phil,

 

Thanks for letting me know about your Ruby port, everything o.k.

 

Cheers,

Wolf
