### ISSUE TITLE
Update NuGet Package to 6.7.0

### ISSUE THREAD

**Issue by artiche** [wolfgarbe/SymSpell#100]
Hello, the latest version in nuget is 6.5.0, do you plan to update the package to version 6.7.0 ?

**Comment by xoofx** [comment]
Hey, I just discovered this library, looks super nice, I would like also to try the latest version, any chance to get an update?

**Comment by wolfgarbe** [comment]
NuGet package has been updated to version 6.7.0

**Comment by xoofx** [comment]
Nice, thanks a lot @wolfgarbe !
