### ISSUE TITLE
Capable of Similarity checks ?

### ISSUE THREAD

**Issue by nhaberl** [wolfgarbe/SymSpell#102]
I am using JARO Winkler distance algo for checking if a given string is similar to another.
Based on the score I show up results.

Now the question is if SymSpell is capable of doing this better / more performant?

``
var score = symspell.CalculateSimilarity(searchText, textFromDatabase)
``

**Comment by wolfgarbe** [comment]
SymSpell is using the Damerau-Levenshtein edit distance algorithm to calculate string similarity. Damerau-Levenshtein is not faster than Jaro-Winkler for basic string similarity comparison (https://stackoverflow.com/a/25540945/1824135), and SymSpell doesn't change that.

SymSpell shines, when you want to find very fast the most similar terms compared to an input string from a very large large dictionary. So **not the single term vs. term comparison is faster**, but **a SymSpell lookup in a large dictionary is much faster** than the naive approach of comparing all n dictionary terms sequentially with the input term, and also much faster than Norvigs approach (generating many similar candidates from the input string, which are then looked up in the dictionary).
