### ISSUE TITLE
WordSegmentation throws exception on any version greater than 6.5.* for some terms

### ISSUE THREAD

**Issue by ashkanparsa** [wolfgarbe/SymSpell#120]
@wolfgarbe thanks for this useful spellchecker! I was using WordSegmentation for a while without any issue but now need to add separator on load dictionary so decided to upgrade the package on c# .net to 6.7.1 but noticed any version greater than 7.5.* is throwing an exception when I call WordSegmentation for some terms like "pattern kimistry". 

parameters:
var symSpell = new SymSpell(16, 2, 7, 1, 5);

call:
var phrase = "pattern kimistry"
symSpell .WordSegmentation(phrase, 1)

exception:
**Index was outside the bounds of the array.**

Is there any way to look into as it's urgent and affected some production features.

Thanks!

**Comment by wolfgarbe** [comment]
Thank you very much for the fix!

**Comment by ashkanparsa** [comment]
you're welcome. Any release timeline for this minor change?
