### ISSUE TITLE
Better usage documentation?

### ISSUE THREAD

**Issue by fireundubh** [wolfgarbe/SymSpell#14]
How are you supposed to integrate SymSpell into a C# project?

I installed the package via NuGet into a .NET 4.6.2 solution.
```csharp
 var symSpell = new SymSpell(initialCapacity, maxEditDistance, prefixLength);
```
This line produces an error in my project: `Cannot create an instance of the abstract class SymSpell`.

Strangely, that same line does not produce an error in the demo project.

As an aside, I had no issues with integrating SymSpellCompound, although the Correct method seemed to only parrot the input words or input text rather than suggest any corrections.

edit: Well, I went ahead and compiled the SymSpell solution, and included the DLL as a reference in my project. I guess that's how? What's the point of the NuGet package then?

edit: Well, the reason why SymSpellCompound wasn't suggesting anything was because the dictionary wasn't loaded, and Lookup wasn't throwing an exception.

**Comment by wolfgarbe** [comment]
SymSpell v5.1 has been refactored from static to instantiated class, the usage example in the readme has been updated accordingly, but the NuGet is still in v5.0. There is currently some ongoing development on the library, once that is finished I will update the NuGet as well.

**Comment by fireundubh** [comment]
All right. Thanks! Great work, by the way.

**Comment by wolfgarbe** [comment]
NuGet has been updated to v6.0. 
Usage is now consistent with the usage example in the readme on GitHub.
