### ISSUE TITLE
Frequency dictionary errors

### ISSUE THREAD

**Issue by fireundubh** [wolfgarbe/SymSpell#15]
Using `frequency_dictionary_en_500_000.txt`, I spotted some errors:

- `youre` should be `you're`
- `dont` should be `don't`
- `dont's` should be `don'ts` 
- Lots of weird `[a-zA-Z]+[0-9]+` words, too.

This list seems to _include_ common misspellings and 1337 speak (e.g., `f1nancially`, `di3`.)

**Comment by wolfgarbe** [comment]
If you want a clean dictionary you should use [frequency_dictionary_en_82_765.txt](https://github.com/wolfgarbe/symspell/blob/master/symspell/frequency_dictionary_en_82_765.txt) , the one that is in the symspell directory. This is derived as intersection between Google Books Ngram data ( Provides representative word frequencies) and SCOWL Spell Checker Oriented Word Lists (Ensures genuine English vocabulary).
See also https://github.com/wolfgarbe/SymSpell#frequency-dictionary

The frequency_dictionary_en_500_000.txt is derived only from Google Books Ngram data and is intended for benchmarking purposes only. It contains common spelling errors and does not ensure genuine English vocabulary.

Probably I should move the test_data directory from SymSpell.Demo to SymSpell.Benchmark to make that clearer.

**Comment by fireundubh** [comment]
Would you be willing to release your code for generating frequency data? I'm in the midst of paring down [Princeton's WordNet databases](https://wordnet.princeton.edu/wordnet/download/current-version/) to word/phrase lists. I could just map the frequencies from your dictionaries, at least to the covered words, but generating new data would probably be more useful.

**Comment by wolfgarbe** [comment]
`
        public static Dictionary<string, Int64> termlist = new Dictionary<string, Int64>();

        //create a word frequency dictionary
        private static void CreateWordFrequencyDictionary()
        {
            //spelling dictionary
            //http://app.aspell.net/create?defaults=en_GB-large
            //http://wordlist.aspell.net/ 
            HashSet<string> hs = new HashSet<string>();
            using (StreamReader sr = new StreamReader(@"scowl2.txt"))
            {
                String line;
                //process a single line at a time only for memory efficiency
                while ((line = sr.ReadLine()) != null)
                {
                    if (line.Length < 1) continue;
                    if (Char.IsUpper(line.Last())) continue; //do not allow abbreviations
                    if ((line.Length <= 2) && Char.IsUpper(line.First())) continue;
                    hs.Add(line.ToLower());
                }
            }


            //### process google ngrams
            //http://storage.googleapis.com/books/ngrams/books/datasetsv2.html

            for (int i = 0; i < 10; i++)
            {
                using (StreamReader sr = new StreamReader(@"googlebooks-eng-1M-1gram-20090715-" + i.ToString() + ".csv"))
                {
                    String line;

                    //process a single line at a time only for memory efficiency
                    while ((line = sr.ReadLine()) != null)
                    {
                        string[] lineParts = line.Split('\t');
                        if (lineParts.Length >= 3)
                        {
                            string key = lineParts[0].ToLower();

                            //allow only terms from the google n-grams which are also in the SCOWL lis
                            if (!hs.Contains(key)) continue;  

                            //allow only terms which start with a letter
                            if (!Char.IsLetter(key.First())) continue;


                            //only a & i are genuine single letter english words
                            if ((key.Length == 1) && (key != "a") && (key != "i")) continue;

                            //addition filters
                            if (key.EndsWith(".")) continue;
                            if ((key.Length == 2) && ((key.StartsWith("'")) || (key.EndsWith("'")))) continue;

                            if (key == "ha") continue;
                            if (key == "te") continue;
                            if (key == "sp") continue;
                            if (key == "th") continue;
                            if (key == "ca") continue;
                            if (key == "yu") continue;
                            if (key == "ms") continue;

                            if (key == "ins") continue;
                            if (key == "ith") continue;
                            if (key == "spp") continue;
                            if (key == "hou") continue;
                            if (key == "ewith") continue;
                            if (key == "fori") continue;

                            
                            //set word counts
                            Int64 count;
                            if (Int64.TryParse(lineParts[2], out count))
                            {

                                //add to dictionary
                                if (termlist.ContainsKey(key))
                                {
                                    termlist[key] += count;
                                }
                                else
                                {
                                    termlist[key] = count;
                                }

                                //Console.WriteLine(key+" "+count.ToString("N0"));
                            }
                        }
                    }
                }
            }

            //add some additional terms
            foreach (string key in new string[15] { "can't", "won't", "don't", "couldn't", "shouldn't", "wouldn't", "needn't", "mustn't", "she'll", "we'll", "he'll", "they'll", "i'll", "i'm", "wasn't" })
            {
                termlist[key] = 300000;
            }

            //sort by frequency
            List<KeyValuePair<string, Int64>> termlist2 = termlist.ToList();
            termlist2.Sort((x, y) => y.Value.CompareTo(x.Value));

            //limit size
            if (termlist2.Count>500000) termlist2.RemoveRange(500000, termlist2.Count - 500000);

            //write new dict to file
            using (System.IO.StreamWriter file = new System.IO.StreamWriter(@"frequency_dictionary_en.txt", false, Encoding.UTF8))
            {

                for (int i = 0; i < termlist2.Count; i++) file.WriteLine(termlist2[i].Key + " " + termlist2[i].Value.ToString());
            }

            Console.WriteLine("ready: " + termlist.Count.ToString("N0") + " terms");

        }
`

**Comment by fireundubh** [comment]
Thanks! I tweaked your code to read ngrams from ZIP archives with SharpZipLib, and changed that for loop to a foreach, so you don't have to hardcode the CSV filename. Works great!

Some questions:

- Any particular reason for using V1 (20090715) over V2 (20120701)? The V2 ngrams are alphabetically sorted and includes transliterated non-Latin scripts. Not sure how much that matters.

- When I generated frequences for the WordNet word list, I noticed all the phrases were removed. How do you deal with terms like "a cappella" and "ipratropium bromide"?

- OT: How do you use both SymSpell and SymSpellCompound together? I think SymSpellCompound can work with phrases, right? (By the way, the InitialCapacity commit in SymSpell does not seem to have made its way to SymSpellCompound. Any plans to integrate compounds into SymSpell?)

**Comment by wolfgarbe** [comment]
> Any particular reason for using V1 (20090715) over V2 (20120701)?

The "English One Million" is only available as Version 20090715. I just wanted the more compact version.

> How do you deal with terms like "a cappella" and "ipratropium bromide"?

Either you spell check the word parts separately (both dictionary and input terms are splitted) or you can take the 2-grams from the Google n-grams and generate a dictionary which contains both 1-grams and 2-grams. Or you just use SymSpellCompound.

> How do you use both SymSpell and SymSpellCompound together?

SymSpellCompound  can work with single terms, phrases and whole sentences. SymSpellCompound  is still based on SymSpell v4.1. Either SymSpellCompound will be integrated into SymSpell or at least updated to the recent code base.
