### ISSUE TITLE
Using different Dataset of words

### ISSUE THREAD

**Issue by irakli97** [wolfgarbe/SymSpell#17]
Dear Wolfgarbe,

I'm currently trying to make this program work for The Georgian language, I made a Dataset of words with their respective frequencies. For some reason, SymSpell does not return my suggestions. I'm sure that it is not SymSpell's fault.  I attached the dataset.
The only difference I see between this and the Demo dataset is that mine is not sorted. So does the sort order matter in this case? or is there some other issue with my dataset?
[workfile.txt](https://github.com/wolfgarbe/SymSpell/files/1544599/workfile.txt)

Sincerely

**Comment by irakli97** [comment]
Sorting helped.

**Comment by wolfgarbe** [comment]
**SymSpell does not require the frequency dictionary text file to be sorted**. But if you load the dictionary with LoadDictionary() it expects  that every word-frequency-pair is in a separate line. A line is defined as a sequence of characters followed by a line feed ("\n"), a carriage return ("\r"), or a carriage return immediately followed by a line feed ("\r\n"). **The problem with your text file was that all word-frequency-pair were within a single line.**

**Comment by irakli97** [comment]
Yah... I also added a new line and carriage returns after sort so probably that helped...
Thanks for reply!
