### ISSUE TITLE
Issue with apostrophes

### ISSUE THREAD

**Issue by whiteazn** [wolfgarbe/symspell#2]
I am working off the java Port of Symspell here (https://github.com/gpranav88/symspell), but I think this error would affect this too?

But looking at the code, @line78 in the `parseWords(text)` function:

`return Regex.Matches(text.ToLower(), @"[\w-[\d_]]+")
                    .Cast<Match>()
                    .Select(m => m.Value);`

It seems to split words such as "shouldn't" into 2 words ("shouldn" and "t").  

Maybe I am wrong here, but shouldn't that be 

`return Regex.Matches(text.ToLower(), @"[\w-[\d_']]+")
                    .Cast<Match>()
                    .Select(m => m.Value);`

so that contractions are added to the dictionary?

**Comment by wolfgarbe** [comment]
You are right, from a practical standpoint words should not be split at apostrophes. There is a simple reason to do it nevertheless: Comparability.
In the accompanying [blog posts](http://blog.faroo.com/2015/03/24/fast-approximate-string-matching-with-large-edit-distances/) there are some benchmarks comparing the performance of SymSpell to the [algorithm of Peter Norvig](http://norvig.com/spell-correct.html). 
It uses a [large text file](http://norvig.com/big.txt) as base for the dictionary. By using the Regex as it is I  make sure that the number of resulting dictionary items is identical to the number of dictionary items generated by Norvigs algorithm.
