### ISSUE TITLE
symspell paper

### ISSUE THREAD

**Issue by hastirad** [wolfgarbe/SymSpell#20]
is there any paper for symspell?
dose symspell detect real word error?

**Comment by wolfgarbe** [comment]
No paper, but several blog posts, which cover algorithms and benchmarks:
[1000x Faster Spelling Correction algorithm](http://blog.faroo.com/2012/06/07/improved-edit-distance-based-spelling-correction/)<br>
[1000x Faster Spelling Correction: Source Code released](http://blog.faroo.com/2012/06/24/1000x-faster-spelling-correction-source-code-released/)<br>
[Fast approximate string matching with large edit distances in Big Data](http://blog.faroo.com/2015/03/24/fast-approximate-string-matching-with-large-edit-distances/)<br> 
[Very fast Data cleaning of product names, company names & street names](http://blog.faroo.com/2015/09/29/how-to-correct-company-names-street-names-product-names/)<br>
[Sub-millisecond compound aware automatic spelling correction](https://medium.com/@wolfgarbe/symspellcompound-10ec8f467c9b)<br>
[SymSpell vs. BK-tree: 100x faster fuzzy string search & spell checking](https://medium.com/@wolfgarbe/symspell-vs-bk-tree-100x-faster-fuzzy-string-search-spell-checking-c4f10d80a078)

What do you mean by "real word error"? 
SymSpell takes an input term and finds the most similar words from the dictionary (within the maximum edit distance). The ability to detect errors depends on how complete the dictionary is.
We have three cases:

1. Symspell returns suggestions, including the original input term:
The input term is a correct word. But is is still possible that we originally wanted to write a different/similar word from the other suggestions.

2. Symspell returns suggestions, but the original input term is not included:
Either the input word contains errors (and there are similar words in the dictionary), or it is correct but not included in the dictionary.

3. SymSpell does not return a suggestion
Either the input word contains errors (and there are no similar word in the dictionary), or it is correct but not included in the dictionary.
