### ISSUE TITLE
File and folder capitalisation problems

### ISSUE THREAD

**Issue by nmstoker** [wolfgarbe/SymSpell#21]
Firstly, thank you for this is project - it looks really impressive.

I'm running this using the .Net Core on Linux and am running into problems with the capitalisation of files and folders when I try **dotnet restore**:

    /opt/dotnet/sdk/2.1.4/NuGet.targets(227,5): warning MSB3202: The project file "/home/neil/Projects/SymSpell/symspell.Demo/symspell.Demo.csproj" was not found. [/home/neil/Projects/SymSpell/SymSpell.sln]

Having cloned the repo from Github, the folder is actually **S**ym**S**pell.Demo with similar differences in the files within those folders (eg SymSpell.CompoundDemo SymSpell.Benchmark)

The fix isn't hard, either change the entries in **SymSpell.sln** to reflect the folders/filenames or adjust those folders/filenames to match the .sln file

I opted to change the folders and files but then had to adjust the location the demo looked for the frequency dictionary as that was looking in the capitalised version of the folder:

    File not found: /home/neil/Projects/SymSpell/SymSpell/frequency_dictionary_en_82_765.txt

I am new to using .Net Core on Linux, so there may be some setting or tip I'm overlooking to help with this, but I suspect if the development is being done on Windows then the problem may have been unnoticed there because Windows tends not to be case sensitive for folders/files whereas Linux is.

Let me know if there are any more details you'd like me to supply for this. Thx!

**Comment by wolfgarbe** [comment]
Thanks! I will fix the capitalisation issue.

**Comment by wolfgarbe** [comment]
Capitalisation issue is fixed now. I had to temporarily remove and restore files and folders from the repository, as github does not correctly synchronize changes of upper/lowercase in filenames/folders.
