### ISSUE TITLE
Page for dictionary cannot be found now

### ISSUE THREAD

**Issue by TimothyShi-kika** [wolfgarbe/SymSpell#23]
Excuse me, but the link points to the dictionary file you use https://github.com/wolfgarbe/SymSpell/blob/master/symspell/frequency_dictionary_en_82_765.txt is reported 404 not found now. Would there be anywhere so I could find the dictionary? Thanks!

**Comment by wolfgarbe** [comment]
The correct link is: https://github.com/wolfgarbe/SymSpell/blob/master/SymSpell/frequency_dictionary_en_82_765.txt
Please note the **camel case** for second SymSpell in the path.

Where did you find the invalid link? Is it in the Medium Blog post?

**Comment by TimothyShi-kika** [comment]
No, I just followed the link provided in the homepage of this project, then saw the 404 not found prompt.

**Comment by wolfgarbe** [comment]
Thanks. The links in the readme have just been fixed.
