### ISSUE TITLE
Can i use Symspell in Android app

### ISSUE THREAD

**Issue by MuneebAhmadMashwani** [wolfgarbe/SymSpell#36]
Hi,
I want to use symspell in android but couldn't find the dependencies to run it in android. How can I bind it with my android app?

Thanks.

**Comment by trans** [comment]
I'm interested in the same. There are Java ports listed in the README, so that would be the first step. Please let me know how it goes for you and I will do the same.

**Comment by wolfgarbe** [comment]
SymSpell targets [.NET Standard v2.0](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) and can be used with
[XAMARIN](https://blog.xamarin.com/history-dot-net-standard/) for Android projects.
