### ISSUE TITLE
Python V6.3 Multiple Space Segmentation

### ISSUE THREAD

**Issue by patronical** [wolfgarbe/SymSpell#45]
The Compound finds single spaces, Segmentation finds multiple spaces.

For the case when many words are concatenated without spaces,
how is Segmentation implemented in Python to add spaces where needed?

**Comment by wolfgarbe** [comment]
Unfortunately the Python implementation of https://github.com/mammothb/symspellpy is not a complete port of SymSpell Version 6.3. 
The [word segmentation](https://towardsdatascience.com/fast-word-segmentation-for-noisy-text-2c2c41f9e8da) method WordSegmentation(string input, int maxEditDistance, int maxSegmentationWordLength) has not been translated fron C# to Python.
You can either try to translate it yourself or open an issue at Github repository of the author of the Python port.
