### ISSUE TITLE
Use as search engine

### ISSUE THREAD

**Issue by mingruimingrui** [wolfgarbe/SymSpell#46]
Hi, How might I use symspell as a search algorithm that returns an index given a query string

**Comment by wolfgarbe** [comment]
A search engine should return all those documents, where all keywords of the query string occur. It is usually based on an [Inverted Index](https://nlp.stanford.edu/IR-book/html/htmledition/a-first-take-at-building-an-inverted-index-1.html).

SymSpell could be used for pre-processing ([Query rewriting/Query expansion](https://queryunderstanding.com/query-rewriting-an-overview-d7916eb94b83)) the query string.
SymSpell could correct spelling errors contained in the query string. The corrected string would then serve as input for a traditional search engine like Lucene/Solr/Elastic, thus increasing the [recall](https://en.wikipedia.org/wiki/Precision_and_recall).
