### ISSUE TITLE
Objective-C or Swift version

### ISSUE THREAD

**Issue by AmitBhavsarIphone** [wolfgarbe/SymSpell#48]
Hi,
This is very efficient and magical way for auto-correction. 
Is it possible for you to provide Objective-c or Swift language version for the same?

It would be very helpful for me in my application.

Thank you.

**Comment by wolfgarbe** [comment]
There used to be a Swift port of SymSpell at https://github.com/Archivus/SymSpell .
Unfortunately the repository has disappeared.

**Comment by AmitBhavsarIphone** [comment]
@wolfgarbe 
Yes, right.

@all readers
If anyone can make Swift or Objective-C port, it would be great start to use this library in native iOS.

We can use this library in Custom keyboards, Texteditor apps and in search logic.

**Comment by reneklacan** [comment]
@AmitBhavsarIphone With some effort, you may be able to make [Rust port](https://github.com/reneklacan/symspell) work with Swift

https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-06-rust-on-ios.html

**Comment by AmitBhavsarIphone** [comment]
@wolfgarbe  
Here is Objective-C version of SymSpell
https://github.com/AmitBhavsarIphone/SymSpell

**Comment by wolfgarbe** [comment]
Thank you! I have included a link to your repository in the readme file.

**Comment by gdetari** [comment]
I have created a Swift implementation: 
https://github.com/gdetari/SymSpellSwift
