### ISSUE TITLE
Suggestion: instantiable class instead of static

### ISSUE THREAD

**Issue by allanchao** [wolfgarbe/symspell#6]
Using SymSpell is great. However, I notice that it's all one static class. This makes it difficult to modify settings for different uses, especially the dictionary and verbosity. It can be helpful to enable this kind of code

`
SymSpell spellingDict1 = new SymSpell(path1, "", 0, 1, 0); // dictionary 1 with verbosity 0
SymSpell spellingDict2 = new SymSpell(path1, "", 0, 1, 1); // dictionary 1 with verbosity 1
SymSpell spellingDict3 = new SymSpell(path1, "", 0, 1, 2); // dictionary 1 with verbosity 2
SymSpell spellingDict4 = new SymSpell(path2, "", 0, 1, 0); // dictionary 2 with verbosity 0
`

the constructor could take the dictionary, or set it later, and optional addional parameters of verbosity, edit distance, lp, etc.

**Comment by wolfgarbe** [comment]
Yes, this has been a frequent request/complaint. I will change this in the next version.

**Comment by wolfgarbe** [comment]
SymSpell has been refactored from static to instantiated class by [Steve Hatchett](https://github.com/softwx). Thanks Steve!
