### ISSUE TITLE
Symmetric Delete spelling correction algorithm

### ISSUE THREAD

**Issue by Dnsh96** [wolfgarbe/SymSpell#64]
Hello sir, thank you for that nice code. I am writing a paper about segmentation of word and fuzzy search of words for certain script. Can i get a detailed algorithm used for this code.

**Comment by wolfgarbe** [comment]
Have a look at the blog posts describing the algorithms
https://github.com/wolfgarbe/SymSpell#blog-posts-algorithm-benchmarks-applications

For anything not clear look into the commented source code itself.
