### ISSUE TITLE
How to give higher priority to a single word correction when using `LookupCompound`

### ISSUE THREAD

**Issue by krasi0** [wolfgarbe/SymSpell#73]
I am using `.LookupCompound(text, 2)` with `frequency_dictionary_en_82_765.txt`
some examples:

`A bycycle` ==> I'd like to get `A bicycle` (the single corrected word `bicycle`) instead of `A by cycle` (`by cycle` is two words here but still syntactically valid)
`Inconvient` ==> to get `Inconvenient` instead of  `I convent`

Any advice on how to get the desired words first? I am sure there is some already existing option for that but I am at a loss finding it.

Thanks in advance! :)

**Comment by wolfgarbe** [comment]
The formula to calculate the combined word occurrence frequency of a split word (which is used to rank/select the best suggestion) in SymSpell.LookupCompound was a mediocre hack.
It is much better to use the Naive Bayes probability of the word combination instead, like we do  already in SymSpell.WordSegmentation.
The Naive Bayes probability of the word combination is the product of the two word probabilities:
P(AB)=P(A)*P(B)

In https://github.com/wolfgarbe/SymSpell/blob/master/SymSpell/SymSpell.cs#L882 just replace

`
suggestionSplit.count = Math.Min(suggestions1[0].count, suggestions2[0].count);
`

`
suggestionSplit.count = (long)((double)suggestions1[0].count / (double)SymSpell.N * (double)suggestions2[0].count);
`
Then your examples will get corrected in the way you expected.

**Comment by krasi0** [comment]
Thank you for your reply! I will try that.
BTW, I use `SymSpell.LookupCompound()` on whole sentences (and even paragraphs) and I am generally satisfied with the results on that level (sentences). Would using Naive Bayes affect (worsen) the performance on the sentence / paragraph level?
Thanks!

**Comment by wolfgarbe** [comment]
Overall it will improve the results, but sometimes you will get worse corrections. That is because the Naive Bayes probability still threats the probabilities of two words independent, although we know that there is a context, that a green car is much more likely than a green mouse.

**Comment by krasi0** [comment]
Right. That makes sense

**Comment by wolfgarbe** [comment]
[New release v6.5](https://github.com/wolfgarbe/SymSpell/releases/tag/6.5) provides better correction quality for LookupCompound with existing single term dictionary by using Naive Bayes probability for selecting best word splitting AND even better correction quality, when using the optional bigram dictionary in order to use sentence level context information for selecting best spelling correction. An English bigram frequency dictionary is included in the release.
