### ISSUE TITLE
Add Java 8 port

### ISSUE THREAD

**Issue by rxp90** [wolfgarbe/SymSpell#82]
Hi
First of all, awesome job, congratulations!
I'm working in a Java version of SymSpell 6.6 so if you can include it in you index it'd be great
https://github.com/rxp90/jsymspell

**Comment by wolfgarbe** [comment]
Thank you for letting me know. Is your port ready yet? Adding a Readme and a License would be great and helpful for your users.

**Comment by rxp90** [comment]
Basic functionality should be there, I'll publish a release as soon as I verify everything is in order :)

**Comment by wolfgarbe** [comment]
Great! I have added the link to your repo.
