### ISSUE TITLE
Is edits generations, needed after getting exact match?

### ISSUE THREAD

**Issue by VJAYSLN** [wolfgarbe/SymSpell#84]
Hello @wolfgarbe , I am using symspell for a last couple of months. I am having some queries on your logic. when giving the dictionary word as input with `Verbosity::ALL ` mode, why it goes for checking deletion entry and other functions.? Why it goes for word edits, even though a exact match founded?
Is that any motivation behind this?

Code For this:-
```
if (words.TryGetValue(input, out suggestionCount))
        {
            suggestions.Add(new SuggestItem(input, 0, suggestionCount));
            // early exit - return exact match, unless caller wants all matches
            if (verbosity != Verbosity.All) goto end;
            // goto end;
        }
```
Thanks in Advance : )

**Comment by wolfgarbe** [comment]
If you select Verbosity.ALL, then SymSpell.Lookup() will return all possible spelling suggestions within the given maxEditDistance, even if an exact match exists.

For example, if your input is cars, it SymSpell will return both cars and card. You see, the s and d key are neighbors on the keyboard. Even if cars is a valid word, perhaps your intention was to write card, you just hit accidentally the wrong neighboring key. 

If you select Verbosity.Top or Verbosity.Closest , then SymSpell.Lookup() will return only the exact match, if an exact match exists.
