### ISSUE TITLE
AttributeError: 'SymSpell' object has no attribute 'build_vocab'

### ISSUE THREAD

**Issue by supreet21** [wolfgarbe/SymSpell#89]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-43-22f740bb76e1> in <module>()
     15 corpus_file_name = 'spell_check_dictionary.txt'
     16 symspell = SymSpell()#verbose=10 omited
---> 17 symspell.build_vocab(
     18     dictionary=corpus,
     19     file_dir=corpus_dir, file_name=corpus_file_name)

AttributeError: 'SymSpell' object has no attribute 'build_vocab'

**Comment by wolfgarbe** [comment]
I guess you refer to some code from Edward Ma, who is using a Python port of SymSpell:
https://github.com/makcedward/nlp/blob/master/sample/util/nlp-util-symspell.ipynb
https://towardsdatascience.com/essential-text-correction-process-for-nlp-tasks-f731a025fcc3
https://github.com/mammothb/symspellpy

Please contact the author of that code directly, as the error you are experiencing is not related to the original SymSpell
