### ISSUE TITLE
[Question] SymSpell How can I use SymSpell to check French language? (I think there's a missing file?)

### ISSUE THREAD

**Issue by ShadyMBA** [wolfgarbe/SymSpell#91]
Hi,

Thanks for the great work. I need to use SymSpell for French. The English version needs 2 files:
frequency_bigramdictionary_en_243_342.txt
frequency_dictionary_en_82_765

In SymSpell.FrequencyDictionary directory there's only one file for French: fr-100k.txt (which is the dictionary)
My question is where I can find frequency_bigramdictionary for French?
It seems to me that one file is missing? Thanks :-)

**Comment by wolfgarbe** [comment]
The bigram dictionary is optional. 

It is  used solely in LookupCompound to improve the correction quality - but it will work also without loading the bigram dictionary. 

Lookup and WordSegmentation do not use the bigram dictionary at all.

But of course you could create your own French bigram dictionary, e.g. by using the [Google Books Ngram data](http://storage.googleapis.com/books/ngrams/books/datasetsv2.html)

**Comment by ShadyMBA** [comment]
Got it! Thank you very much for your punctual reply :-)
