### ISSUE TITLE
Trie in Symspell

### ISSUE THREAD

**Issue by MighTguY** [wolfgarbe/SymSpell#92]
Hi @wolfgarbe ,
Greetings 
Currently, we use Dictionary/Map for holding data?
can we move it to a more optimized trie?

similar to your repo  **PruningRadixTrie** (https://github.com/wolfgarbe/PruningRadixTrie)

**Comment by wolfgarbe** [comment]
Of course we could use a Trie instead of a Dictionary/Map for holding the deletes. But I don't think there will be a benefit, neither in lookup speed nor in memory consumption. But I will do a quick experiment to verify that.

**Comment by wolfgarbe** [comment]
Test results: 500.000 terms from frequency_dictionary_en_500_000.txt resulting in 12.577.734 deletes:

Radix trie<string,long>:        1800 MB    
Dictionary<string,long>:       1366 MB    
Dictionary<uint hash, long>:  600 MB     

The dictionary is more space efficient than the trie. For spelling suggestion I use a trie for prefix  range search. But for SymSpell this is not required, I just need a simple key lookup.

Of course there are ways to optimize the space efficiency of tries, e.g. [Succinct Tries ](http://stevehanov.ca/blog/?id=120). But they are slow.
