### ISSUE TITLE
using accent mark

### ISSUE THREAD

**Issue by alet149** [wolfgarbe/SymSpell#94]
I am using symspell library in c#, I have a spanish corpus, but I have a problem when the correct word has accent mark. The problem is the edit distance in the correct word is largest than no correct word. This is my case:
bad word: MEDEĽTIN
word correct in dictionary: medellín
suggestions list returned with edit distance max, Frequency:
   medefin 2, 6
   Medellin 3, 14671
What can I do? thanks

**Comment by alet149** [comment]
thanks Wolf, I had a mistake when I wrote my case. In the dictionary I have this:
medefin 6
medellín 14671}

**bad word**: MEDEĽTIN

when i run lookup method with verbosity= All, I receive this suggestions list :
[0], {{medefin, 2, 6}}
[1], {{medellín, 3, 14671}}
[2], {{medestia, 3, 30871}}
.
.
.
I attached image
![suggestions](https://user-images.githubusercontent.com/33134934/90986526-3606a580-e549-11ea-9493-0f51f2d06b62.png)

Thanks for your help!

**Comment by wolfgarbe** [comment]
In SymSpell (and in UTF-8) letters with and without or with different accents are treated as different letters.
Therefore they differ and have a large edit distance, even if they *look* similar or *sound* similar (I don't know how those letters in Spanish are pronounced).
And this is reasonable, as you probably want to correct words with a wrong accent
In your example both the Ľ and l are treated as different letters, as well as I and í are treated as different letters.

That said, you can remove the accent (https://en.wikipedia.org/wiki/Diacritic) from letters, and transform the letters to their root form. Then the edit distance will be closer to that what you are probably expecting. 

You can do this as a post-processing step. Use the unmodified SymSpell, get the suggestion list, remove the accents from both the input term and the suggestions.
Re-calculate the Damerau-Levenshtein edit distance, and re-sort the suggestion list according to the new edit distance.


```

public static String RemoveDiacritics(string s)
{
	String normalizedString = s.Normalize(NormalizationForm.FormD);

	if (normalizedString != s)
	{
		StringBuilder stringBuilder = new StringBuilder();
		for (int i = 0; i < normalizedString.Length; i++)
		{
			Char c = normalizedString[i];
			if (CharUnicodeInfo.GetUnicodeCategory(c) != UnicodeCategory.NonSpacingMark)
				stringBuilder.Append(c);
		}
		return stringBuilder.ToString();
	}
	else return s;
}


string[] termList= new string[] { "MEDEĽTIN", "medefin", "medellín", "medestia" };
foreach (string s in termList) Console.WriteLine(s+" "+ RemoveDiacritics(s.ToLower()));


```
Output:

MEDELTIN medeltin
medefin  medefin
medellín medellin
medestia medestia
