### ISSUE TITLE
[Question] How to adhoc setup an own dictionary

### ISSUE THREAD

**Issue by CobraCalle** [wolfgarbe/SymSpell#95]
Hello,

I`m looking for a way to find entries out of a list from speach recognition result. For example I have a list of radio stations and the use would like to select one by voice... often the recognised speach, does not exactly matches the radio station name (for example "RaumeMusik.fm lounge" and "raute music lounge"... now I would like to find the closest defined radio station...

How can I setup my own "dictionary" with the list of defined radio stations to use symspell to find the closest?

thank you very much

**Comment by wolfgarbe** [comment]
```

//create object
int initialCapacity = 100;
int maxEditDistanceDictionary = 3; //maximum edit distance per dictionary precalculation
var symSpell = new SymSpell(initialCapacity, maxEditDistanceDictionary);
      
//load dictionary
symSpell.LoadDictionary("station_names.txt", 0, 1,new char[] { ','})

//lookup suggestions for single-word input strings
string inputTerm="raute music lounge";
int maxEditDistanceLookup = 1; //max edit distance per lookup (maxEditDistanceLookup<=maxEditDistanceDictionary)
var suggestionVerbosity = SymSpell.Verbosity.Closest; //Top, Closest, All
var suggestions = symSpell.Lookup(inputTerm, suggestionVerbosity, maxEditDistanceLookup);

//display suggestions, edit distance and term frequency
foreach (var suggestion in suggestions)
{ 
  Console.WriteLine(suggestion.term +" "+ suggestion.distance.ToString() +" "+ suggestion.count.ToString("N0"));
}

```

**station_names.txt**  (all dictionary entries in lower case, terms may contain white space, the word frequency in the dictionary is not important for your use case, but can be used to rank/prioritize suggestions, if their edit distance is equal)

```
raumemusik.fm lounge,10
energy berlin,10
star sat radio,10
antenne bayern,10

```

**Comment by CobraCalle** [comment]
Thank you very much for your help...

I tried to adapt your sample (because I want to create the dictionary adhoc and would like a avoid creating / reading a file)...

            var symSpell = new SymSpell(100, 3);

            var dictionary = new StringBuilder();

            dictionary.AppendLine("raumemusik.fm lounge,10");
            dictionary.AppendLine("energy berlin,10");
            dictionary.AppendLine("star sat radio,10");
            dictionary.AppendLine("antenne bayern,10");

            using (var dictionaryStream = new System.IO.MemoryStream())
            using (var dictionaryStreamWriter = new System.IO.StreamWriter(dictionaryStream))
            {
                dictionaryStreamWriter.WriteLine("raumemusik.fm lounge,10");
                dictionaryStreamWriter.WriteLine("energy berlin,10");
                dictionaryStreamWriter.WriteLine("star sat radio,10");
                dictionaryStreamWriter.WriteLine("antenne bayern,10");

                dictionaryStreamWriter.Flush();

                dictionaryStream.Position = 0;

                symSpell.LoadDictionary(dictionaryStream, 0, 1);
            }


            string inputTerm = "raute music lounge";
            int maxEditDistanceLookup = 3; //max edit distance per lookup (maxEditDistanceLookup<=maxEditDistanceDictionary)
            var suggestionVerbosity = SymSpell.Verbosity.Closest; //Top, Closest, All
            var suggestions = symSpell.Lookup(inputTerm, suggestionVerbosity, maxEditDistanceLookup);

            //display suggestions, edit distance and term frequency
            foreach (var suggestion in suggestions)
            {
                Console.WriteLine(suggestion.term + " " + suggestion.distance.ToString() + " " + suggestion.count.ToString("N0"));
            }

But the result is an empty array of suggestions.

I`ve noticed that the CreateDictionary-method does not have a char-array-parameter (I`m using the latest nuget)... could that be to problem?

**Comment by CobraCalle** [comment]
OK... I found the problem... maxDicEditDistance = 3 is not enough for the sample... 6 will work
