### ISSUE TITLE
Improve discoverability of SymSpell

### ISSUE THREAD

**Issue by NickStrupat** [wolfgarbe/SymSpell#97]
I believe SymSpell is not being discovered by many who are searching for fuzzy search solutions. I, for one, worked on a fuzzy matching system for a couple years and never came across SymSpell. Now that I've known about it for a year or so, I still have trouble finding it when I forget the name.

For example,

[https://github.com/search?l=C%23&o=desc&q=fuzzy+search&s=stars&type=Repositories](https://github.com/search?l=C%23&o=desc&q=fuzzy+search&s=stars&type=Repositories)

doesn't return SymSpell. I believe it's because `GitHub` only searches the repo name and the 'about' field, the latter of which does not include any permutation of `fuzzy` nor `search`.

Love the project, just want it to be discoverable by more who are looking!

**Comment by wolfgarbe** [comment]
Thank you for letting me know. I have added "fuzzy search" to the about field.

**Comment by NickStrupat** [comment]
Excellent! I see it now at the top of the list when I use that search query (also sorted by "Best Match").
